#!/bin/sh
dir_backups=/home/backups/HOME
password=$(pass pc/backups)

if [[ -z $password ]]; then
    echo 'empty password'
    exit 1
fi

for dir in $HOME/{documents,music,pictures,videos}; do
    # backup only directories that exist
    if [[ ! -d $dir ]]; then
        echo "skipping non-existing dir ${dir}"
        continue
    fi

    # file names
    dirname=$(basename $dir)
    archive="backup_$(date +%Y-%m-%d)__${dirname}.tgz"

    # skip backup if already backed up
    if [[ -f ${dir_backups}/$archive.gpg ]]; then
        echo "skipping ${dir}, backup already exists"
        continue
    fi

    # skip compression if already compressed
    if [[ ! -f $dir_backups/$archive ]]; then
        echo "compressing $dir"

        # change to parent directory before running tar
        cd $(dirname $dir)

        # compress the directory
        tar czf $archive $dirname

        # move archive to where it's gonna be encrypted
        mv $archive $dir_backups
    fi

    # re-enter backup dir, where the encrypted file will be stored
    cd $dir_backups
    echo "encrypting $dir"

    # encrypt the archive
    echo $password | gpg --batch --passphrase-fd 0 -c "$archive"

    # remove it
    rm "$archive"
done
