#!/bin/sh

function getPerlRegex()
{
  local regex="$1"
  shift
  while [[ -n $1 ]]; do
    regex="$regex|$1"
    shift
  done
  echo -n "^($regex)$"
}

function getColumnNumbers()
{
  regex=$(getPerlRegex "$@")
  head -n 1 < /dev/stdin | tr ',' '\n' | sed 's/"//g' |
	  grep -n -P "$regex" |  grep -o -P '^[0-9]+'
}

function getAwkCommand()
{
  echo -n '{printf '
  getColumnNumbers "$@" < /dev/stdin |
    awk '{printf "$"$1" "}' | sed 's/ /" | "/g' | sed 's/" | "$//'
  echo -n '"\n"}'
}


function filterColumns()
{
  tmpFile=$(mktemp)
  cat /dev/stdin > $tmpFile
  awkCommand=$(getAwkCommand "$@" < $tmpFile)
  awk -F , "$awkCommand" < $tmpFile
  rm $tmpFile
}

filterColumns "$@"
