#!/bin/sh
applications_list=$HOME/.config/applications.list
application_name=$(sed 's/:.*//' $applications_list | sort | rofi -dmenu -window-title 'application')
[[ -z $application_name ]] && exit 0
application_cmd=$(grep "$application_name" $applications_list | sed 's/.*://' )
$SHELL -c "$application_cmd"
exit 0
