#!/bin/sh
cd $PASSWORD_STORE_DIR
account=$(fd -t f -x echo '{.}' | rofi -dmenu -window-title 'password')
[[ ! -f "$account.gpg" ]] && exit 1
clipctl disable
pass show $account --clip
clipctl enable
exit 0
