#!/bin/sh
(
	if [[ -n $@ ]]; then
		echo $@
	else
		cat /dev/stdin
	fi
) | 
sed 's/[ \_]/-/g' \                  # replace space or underline with hyphen
 -e 's/\([a-z]\)\([A-Z]\)/\1-\2/g' \ # split camel/pascal case words
 -e 's/[-]\+/-/g' \                  # supress consecutive hyphens
 -e 's/-\?\([\[(){}]\)-\?/\1/g' \    # delete hyphens surrounding parenthesis/braces/brackets
 -e 's/-\?\]-\?/]/g' \               # delte hyphens surrounding the character ']'
 -e 's/^-//g' \                      # trim hyphen at the beginning of sentence
 -e 's/-$//g' \                      # trim hyphen at the end of sentence
 -e 's/.*/\L&/g'                     # convert everything to lower case
  >&1                                # redirect output to stdout
exit 0
