#!/bin/sh
rsa_dir=~/.local/share/ssh
rc_file=~/.config/urk/urk.rc

cd $rsa_dir

function show_help()
{
	cat <<EOF
Unlock rsa keys whose password is encrypted with PGP.
EOF
}

function unlock_all()
{
	for file in id_rsa*; do
		if [[ "$file" =~ .pub$ ]]; then
			continue
		fi
		name=${file/id_rsa_/}
		unlock $name
	done
}

function list_keys()
{
	ls id_rsa* | grep -v .pub$ | sed 's/id_rsa_//'
}

function unlock()
{
	name=$1

  if [[ -f $rc_file ]]; then
    key_alias=$(grep -P "^$name" $rc_file | awk '{ print $2}')
    if [[ -n key_alias ]]; then
      name="$key_alias"
    fi
  fi

  file=id_rsa_${name}
	if [[ ! -f $file ]]; then
		echo "key does not exit"
		return 1
	fi

	key_name=rsa/${name}
	password=$(pass $key_name)

	if [[ -z $password ]]; then
		echo "empty password"
		return 1
	fi

	expect>/dev/null <<EOF
	set timeout -1
	spawn ssh-add $file
	match_max 100000
	expect -exact "Enter passphrase for $file: "
	send -- "$password\r"
	expect eof
EOF
}

function main()
{
	[[ -z $1 ]] && echo "Nothing to do" && return 0;
	case $1 in
		-a|--all)
			unlock_all
			;;
		-h|--help)
			show_help
			;;
		-l|--list)
			list_keys
			;;
		*)
			while (( $# > 0 )); do
				unlock $1
				shift
			done
			;;
	esac
}

main "$@"

exit 0
