#!/bin/bash

# Show the number of files in a directory
# @param {string} $directory
help() {
	echo -e "Description:\n\tList the number of files in the specified directory\n"
	echo -e "Usage:\n\tnumfiles [FLAGS] [DIRECTORY]\n"
	echo -e "Example:\n\tnumfiles /dev'\n\tnumfiles -r /dev\n"
}

numfiles_recursive() {
	echo "$(find $1 -type f | wc -l)"
}

numfiles_nonrecursive() {
	echo "$(ls $1 | wc -l)"
}

recursive=0
dir="${1:-$(pwd)}"

case $1 in
	-h|--help)
		help
		exit 0
		;;&
	-r|-R|--recursive)
		dir="${2:-$(pwd)}"
		recursive=1
		;;&
	*)
		;;
esac

if ! [[ -d $dir ]]; then
	echo "ERROR: Cannot access $dir. No such file or directory" >&2;
	exit 1
fi

if [[ $recursive -eq 1 ]]; then
	numfiles_recursive $dir
else
	numfiles_nonrecursive $dir
fi

exit 0
