#!/bin/bash

help() {
	echo -e "Description: Rename files recursively in the specified directory using the given command."
	echo -e "Usage: rename-files [COMMAND] [DIRECTORY=pwd]"
	echo -e "Examples:"
	echo -e "\trename-files \"tr 'A-Z' 'a-z'\" .. \n"
	echo -e "\trename-files \"sed 's/.js/.ts/' webfiles/ \" \n"
}

if [[ $1 == "--help" ]] || [[ $1 == "-h" ]]; then
	help
	exit 0
fi

rename_file() {
	path="$@"
	basename=${1##*\/}
	dir=${1%\/*}
	newname=$(echo $basename | $rename_function)
	if [[ "$basename" != "$newname" ]]; then
		mv "$path" "$dir/$newname"
	fi
}

rename_files() {
	fd . "$@"  --max-depth 1 |
	while read file; do
		if [[ -d "$file" ]]; then
			rename_files "$file"
		fi
		rename_file "$file"
	done
}

rename_function=$1
dir=${2:-$(pwd)}

if ! [[ -d $dir ]]; then
	echo "ERROR: there is no such directory" >& 2
	exit 1
fi

rename_files $dir
