#!/bin/bash

url=$1
destination=~/downloads/webpages/

if [[ -z $1 ]]; then
	echo "ERROR: empty url"
	exit 1
fi

cd $destination
wget --adjust-extension --span-hosts --convert-links --backup-converted --page-requisites $url

exit 0
