#!/bin/sh
# exit if Xserver or daemon are not running.
xset q >/dev/null || pidof notification-daemon>/dev/null || exit 1;

# get information about battery
battery_level=$(acpi | sed 's/.*:[^0-9]*\([0-9]\+\)%.*/\1/')
charging=$(acpi | grep Charging)

# exit if is charging or battery is above 20%
(( $battery_level > 20 )) && exit 0;
[[ -n $charging  ]] &&  exit 0;

# notification options
time='5000'
title='LOW BATTERY'
message="Battery is only $battery_level%."
icon='battery-caution'
urgency='critical'

# send notification
notify-send -i "$icon" -t "$time" -u "$urgency" "$title" "$message"
echo sent
exit 0
