" source the configuration files
source $VIMRC-options
source $VIMRC-xdg
source $VIMRC-gvim
source $VIMRC-plugins
source $VIMRC-bugfixes
source $VIMRC-keymaps
source $VIMRC-autocommands
source $VIMRC-abbreviations
source $VIMRC-functions
