" source the configuration files
source $VIMRC-general
source $VIMRC-xdg
source $VIMRC-gui
source $VIMRC-plugins
source $VIMRC-bugfixes
source $VIMRC-keybindings
source $VIMRC-autocommands
source $VIMRC-abbreviations
source $VIMRC-userfunctions
