#!/bin/sh

# file used to store last visited dir
cached_file=${HOME}/.cache/fp
default_download_dir=${HOME}/downloads
touch "${cached_file}"

# set dir to last visited dir or to ~/downloads
lines=$(wc -l "${cached_file}" | grep -o '^[0-9]')
if [ "${lines}" -gt 0 ]; then
  dir=$(head -n 1 "${cached_file}")
  dir=$(dirname "${dir}")
else
  dir=$default_download_dir
fi

[ -d "${dir}" ] || dir=$default_download_dir

# get the args to pass to ranger
flags=$1
file=$2
tmpfile=$(mktemp)

# launch ranger on a terminal
kitty --class Ranger -e ranger "${flags}" "${tmpfile}" "${dir}" 2>/dev/null
cp "${tmpfile}" "${file}"

# update last visited dir
lines=$(wc -l "${tmpfile}" | grep -o '^[0-9]')
if [ -n "${lines}" ] && [ "${lines}" -gt 0 ]; then
  cp "${tmpfile}" "${cached_file}"
fi

# rm tmp file
rm "${tmpfile}"
