#!/bin/bash
applications_list=${HOME}/.config/applications.list
tmp=${applications_list}.tmp

while read line; do
  application_name=$(echo "${line}" | sed 's/^[a-z\d_-]\+: //i' | awk '{print $1}')
  builtin type -p "${application_name}" >/dev/null && echo ${line}
done < "${applications_list}" > "${tmp}"

application_name=$(sed 's/:.*//' "${tmp}" | rofi -dmenu -window-title 'application' | head -n 1)
[ -z "${application_name}" ] && exit
application_cmd=$(grep "^${application_name}" "${tmp}" | sed 's/.*: //' )
exec $application_cmd
