#!/bin/sh

function showHelp() {
  cat << EOF
volumectl - Volume Controller

Usage
  volumectl [command] [args]

Description
  volumectl is a simple frontend script to control audio volume. It uses pamixer behind the scenes and send signals to dwmblocks whenever audio is changed.

Commands
  inc, -i [AMMOUNT]
    Incrase audio volume by the given ammount.
  dec, -d [AMMOUNT]
    Decrease audio volume by the given ammount.
  set, -s [AMMOUNT]
    Set audio volume to the given ammount.
  get, -g
    Get the current audio volume.
  mute, -m
    Mute audio.
  unmute, -M
    Unmute audio.
  toggle-mute, -t
    Toggle mute audio.
EOF
exit 0
}

action=$1
ammount=$2

case $action in
  inc|-i)
    pamixer --unmute
    pamixer --allow-boost --increase $ammount
    ;;
  dec|-d)
    pamixer --unmute
    pamixer --allow-boost --decrease $ammount
    ;;
  set|-s)
    pamixer --toggle-mute
    pamixer --allow-boost --set-volume $ammount
    ;;
  get|s)
    pamixer --get-volume
    ;;
  mute|-m)
    pamixer --mute
    ;;
  unmute|-M)
    pamixer --unmute
    ;;
  toggle-mute|-t)
    pamixer --toggle-mute
    ;;
  *)
    showHelp
    ;;
esac

pkill --signal 10 dwmblocks
pkill -SIGRTMIN+10 i3blocks
exit 0
