#!/bin/sh
if [ $# = 2 ]; then
  option="${1}"
  file="${2}"
elif [ $# = 1 ]; then
  option="--all"
  file="${1}"
else
  echo 'ERROR: invalid argument format'
  exit 1
fi

case "$option" in
  --extension|-e)
    basename=${file##*/}
    extension=${basename##*\.}
    [ "${extension}" != "${basename}" ] && echo "${extension}"
    ;;
  --base-name|-N)
    echo "${file##*/}"
    ;;
  --directory|-D)
    dir=${file%/*}
    if [ "${file}" = "${dir}" ]; then
      echo '.'
    else
      echo "${dir}"
    fi
    ;;
  --base-directory|-d)
    dir=${file%/*}
    basedir=${dir##*/}
    if [ "${file}" = "${basedir}" ]; then
      echo '.'
    else
      echo "${basedir}"
    fi
    ;;
  --filename|-n)
    basename=${file##*/}
    echo "${basename%.*}"
    ;;
  --all|-a)
    basename=${file##*/}
    filename=${basename%.*}
    extension=${basename##*\.}
    if [ "${extension}" = "${basename}" ]; then
      extension=""
    fi
    dir=${file%/*}
    if [ "${dir}" = "${file}" ]; then
      dir=.
    fi
    basedir=${dir##*/}
    cat <<EOF
path: "${file}"
directory: "${dir}"
base name: "${basename}" 
file name: "${filename}"
extension: "${extension}"
base directory: "${basedir}"
EOF
    ;;
  *)
    echo 'ERROR: invalid option'
    exit 1
esac

exit 0
