#!/bin/sh

# ------------------------------------------------
# SHELL ALIASES
# ------------------------------------------------

# shortcuts --------------------------------------------------------------------

alias a='aliases'
alias b='$BROWSER'
alias c='coins'
alias e='envvars'
alias f='myfunctions'
alias g='git'
alias h='hist'
alias m='neomutt'
alias n='newsboat'
alias o='open'
alias p='profile'
alias q='exit'
alias s='sxiv'
alias t='touch'
alias v='nvim'
alias y='yay'

# more shorctus ----------------------------------------------------------------

alias oc='octave'
alias py='python'
alias rr='ranger'
alias s.='s .'
alias v.='v .'
alias vv='v ~/.config/vim'
alias xx='startx'
alias za='tabbed -c zathura -e'

# files ------------------------------------------------------------------------

alias  l='exa --color=never'
alias ls='exa --color=never'
alias la='exa --color=never -lhgH --group-directories-first --all'
alias ll='exa --color=never -lhgH --group-directories-first'
alias l1='exa --color=never -1hgH --group-directories-first'

# long-name programms -----------------------------------------------------------

alias open='xdg-open'
alias rename='perl-rename'
alias poweroff='loginctl poweroff'
alias reboot='loginctl reboot'
alias off='poweroff'

# clipboard stuff ---------------------------------------------------------------

alias xcopy='xclip -selection clipboard'
alias xpaste='xclip -selection clipboard -out'

# programms with default options -----------------------------------------------

alias python='python -q'
alias octave='octave -q'
alias R='R -q'

# shells -----------------------------------------------------------------------

alias bash='SHELL=/bin/bash bash'
alias zsh='SHELL=/bin/zsh zsh'

# git --------------------------------------------------------------------------

alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gC='git clone'
alias gd='git diff'
alias gs='git status --short'
alias gk='git checkout'
alias gl='git log --oneline'
alias gg='git log --oneline --graph --full-history --all'

# docker -----------------------------------------------------------------------

alias dk='docker'
alias dkps='docker ps'
alias dke='docker exec'
alias dkei='docker exec -it'
alias dker='docker exec --user root'
alias dkeir='docker exec -it --user root'

# docker-compose ---------------------------------------------------------------

alias dup='docker-compose up -d'
alias ddown='docker-compose down'

# docker programs --------------------------------------------------------------

alias erd='docker run -i erd'

# Laravel ----------------------------------------------------------------------

alias pa='php artisan'
alias pam='php artisan migrate'
alias par='php artisan route:list --compact'
alias tinker='php artisan tinker'

# Java Algs4 ------------------------------------------------------------------

alias ja='java-algs4'
alias jac='javac-algs4'

# npm --------------------------------------------------------------------------

alias naudit='npm audit'
alias nauditf='npm audit fix'
alias npublish='npm publish --access=public'

# npm scripts ------------------------------------------------------------------

alias nbuild='npm run build'
alias ndev='npm run dev'
alias ndev-js='npm run dev-js'
alias ndev-css='npm run dev-css'
alias nprod='npm run prod'
alias nprod-js='npm run prod-js'
alias nprod-css='npm run prod-css'
alias nrun='npm run'
alias nserve='npm run serve'
alias nwatch='npm run watch'
alias nwatch-js='npm run watch-js'
alias nwatch-css='npm run watch-css'

# pacman -----------------------------------------------------------------------

alias pqeq='pacman -Qeq'
alias pss='pacman -Ss'
alias ppr='sudo pacman -Rsn'
alias pS='sudo pacman -S'
alias pp='sudo pacman -Syu'

# yay --------------------------------------------------------------------------

alias yqeq='yay -Qeq'
alias yss='yay -Ss'
alias yyr='yay -Rsn'
alias yS='yay -S'
alias yy='yay -Syu'

# XDG dirs ---------------------------------------------------------------------

alias ssh='ssh -F ${XDG_CONFIG_HOME}/ssh/config'
alias scp='scp -F ${XDG_CONFIG_HOME}/ssh/config'
alias startx='startx ${XINITRC} -- ${XSERVERRC} vt1'

# mixed

alias myip='curl -s https://api.ipify.org'
