#!/bin/sh

#############################
##     SHELL FUNCTIONS     ##
#############################

# append directory to path if not included already
function path_append() {
  while [[ -n $1 ]]; do
    dir=$1
    if [[ -d "${dir}"  ]] && [[ ":${PATH}:" != *":${dir}:"*  ]]; then
      export PATH="${PATH}:${dir}"
    fi
    shift
  done
  return 0
}

# prepend directory to path if not included already
function path_prepend() {
  while [[ -n $1 ]]; do
    dir=$1
    if [[ -d "${dir}"  ]] && [[ ":${PATH}:" != *":${dir}:"*  ]]; then
      export PATH="${dir}:${PATH}"
    fi
    shift
  done
  return 0
}

# utility to add, edit, view, or sync shell aliases
function aliases() {
  aliases_file=${XDG_CONFIG_HOME}/shell/aliases
  case "$1" in
    edit|-e) $EDITOR $aliases_file ;;
    sync|-s) source $aliases_file ;;
    add|-a)
      shift
      name=$1
      shift
      echo "alias $name='$@'" >> $aliases_file
      ;;
    rm|-r)
      name=$1
      sed -i "alias $1/d"  $aliases_file
      ;;
    *) alias ;;
  esac
  return 0
}

# utility to edit, view, or sync shell profile
function profile() {
  profile_file=${XDG_CONFIG_HOME}/shell/profile
  case "$1" in
    edit|-e) $EDITOR $profile_file ;;
    sync|-s) source $profile_file ;;
    *) $PAGER $profile_file ;;
  esac
  return 0
}

# utility to edit, view, or sync shell functions
function fn() {
  file=${XDG_CONFIG_HOME}/shell/functions
  case "$1" in
    edit|-e) $EDITOR $file ;;
    sync|-s) source $file ;;
    *) $PAGER $file ;;
  esac
  return 0
}

# utility to edit, view, or syn environment variables
function envs() {
  env_file=${XDG_CONFIG_HOME}/shell/env
  case "$1" in
    edit|-e) $EDITOR $env_file ;;
    sync|-s) source $env_file ;;
    view|-v) $PAGER $env_file ;;
    *) env ;;
  esac
  return 0
}

# Go back to the parent directory n times
function up() {
  number="${1:-1}"
  for i in $(seq $number); do
    cd ..
  done
  return 0
}

# Make a directory and cd into it
function mkcd() {
  mkdir -p "$1" && cd "$1"
  return 0
}


# Run a command n times
function repeat() {
  n="${1:-1}"
  shift
  command="$@"
  for i in $(seq $n); do
    sh -c "$command"
  done
  return 0
}

# utility to view cryptocurrency market
function ratex() {
  case $1 in
    -c|--currency)
      shift
      currency=$1
			shift
      curl "$currency.rate.sx/$@"
      return 0
      ;;
    *)
      curl "rate.sx/$@"
      return 0
      ;;
  esac
}
