#!/bin/sh

if [ -z "$(pidof ssh-agent)" ]; then
	[ -f /usr/bin/ssh-agent ] && eval "$(ssh-agent)" && echo ssh-agent started
fi

if [ -z "${DBUS_SESSION_BUS_PID}" ]; then
	export $(dbus-launch) && echo dbus launched
fi
