#!/bin/sh

#############################
##      SHELL PROFILE      ##
#############################

# name of the shell (bash, zsh, or sh)
shell=${SHELL##*/}

# load shell configuration 
SHELL_CONFIG=~/.config/shell
[[ -f $SHELL_CONFIG/env ]] && source $SHELL_CONFIG/env
[[ -f $SHELL_CONFIG/aliases ]] && source $SHELL_CONFIG/aliases
[[ -f $SHELL_CONFIG/functions ]] && source $SHELL_CONFIG/functions

# load local scripts
path_append ~/.local/scripts ~/.local/bin  ~/.local/bin/AppImages

# load zoxide
[[ -f /usr/bin/zoxide ]] && eval "$(zoxide init $shell)"

# load fzf
fzf_dir=/usr/share/fzf
fzf_bindings=${fzf_dir}/shell/key-bindings.${shell}
fzf_completion=${fzf_dir}/shell/completion.${shell}

[[ -f $fzf_bindings ]] && source $fzf_bindings
[[ -f $fzf_completion ]] && source $fzf_completion

# set tabsize to 2
tabs -2
