#!/bin/sh

#############################
##      SHELL PROFILE      ##
#############################

# handy helper
function source_files()
{
  while (($# > 0)); do
    local file=$1
    [[ -f $file ]] && source $file
    shift
  done
  return 0
}

# name of the current shell: (bash, zsh, sh, or other)
shell=${SHELL##*/}

# load environment variables, aliases, and user funtions.
SHELL_CONFIG=~/.config/shell
source_files $SHELL_CONFIG/{env,aliases,functions}

# load local scripts and local bin
path_append ~/.local/{bin,scripts}

##### SHELL COMPLETION ######

# source custom shell completion and keybindings
source_files $SHELL_CONFIG/{keybindings,completion}/*.$shell

# zoxide completion
[[ -f /usr/bin/zoxide ]] && eval "$(zoxide init $shell)"

# qpdf completion
[[ -f /usr/bin/qpdf ]] && eval "$(qpdf --completion-${shell})"

# set tabsize to 2
tabs -2
